### PR TITLE
support query data in viewmodel

### PR DESCRIPTION
**Pull request by zyknow**
This PR introduces a feature found at https://github.com/AvaloniaInside/Shell/issues/11#issue-1902105864.

The main purpose of this feature is to find InstanceViewModel properties and set their values.

Here's an example on how to use it:

- image

- image

We have also added an example in SecondView.

### CODE REVIEW

**Comment by OmidID** [comment]
Hello @zyknow 
I can see this is a draft PR but I can leave some comments for you.

1. The place you implemented is not correct, the job of the navigator is different than processing argument.
2. This feature should be an extension because this feature can cause performance issues.
3. There are many changes such as formatting files which are useless and make the review of PR very hard. 
4. I can see you are using Navigator from the home page to the second page instead of automatic with the attached property. This feature should be implemented in a way that can work in both ways.
5. Maui used different ways to implement and they used a dictionary, So they used less generic execution.

Overall, it should be implemented in different ways to stay in the same application architecture.

**Comment by zyknow** [comment]
Thank you for your response and comments, and for correcting my mistakes. 
It's possible that I didn't fully understand this Shell code and also i have some question.

Here is my understanding for you comments
1,2,5 : add extensions for NavigationService maybe better,arguments in this extensions use `Dictionary` type maby better.
3      : i will doing better in next commit, thank you for helping me correct the problem.
4      : i think to implemented attached way is difficult for me. or you can tell me how to do it.


about performance in my implemented is use Reflection, may make AOT more difficult, I'm not sure.

**Comment by OmidID** [comment]
Hello again @zyknow 

I meant that an extension to be optional can enable feature flipping or replace a service. 
This feature can be implemented in a new navigation update strategy. 

After I reviewed the MAUI, I understood the query can be applied on Page not View model and the only way to use parameters at View Model is IQueryAttributable. This is back to the query string from the path and not the argument. the dictionary is the additional way to pass parameters which is this Shell has a different way to pass argument. 

We already have query string passing but we never used it, so you can focus on that.

So. You never need to change Home page code from the attached property to the navigator service. the second page. because of 2 reasons, first, you can pass the argument as CommandParameter, and second thing because you can pass path.

I hope it is clear.

**Comment by zyknow** [comment]
Thank you for your patient explanation. Now I understand.
i will commit a new pull request later.

**Pull request closed without merging**
